### ISSUE TITLE
Time functions for deformation model functional model

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#18]
The strawman proposal for a time function is:

The time function is one of:

- a piecewise linear function of time. Specialisations of the piecewise linear time function are:
   - constant value
   - constant velocity
   - step function
- an exponential function

Piecewise linear functions are defined by an ordered set of time/date values and a corresponding set of scale factors defining the value by which the spatial model is multiplied at that time. The functions are not necessarily continuous – for example the model may define step function. The date/time values should be increasing. Where there is a step function the series will include two consecutive identical date/time values.

@rstanaway commented: 

> The postseismic decay part of the functional model could be represented by composite logarithmic and exponential decay functions (e.g. logarithmic + logarithmic + exponential, logarithmic + exponential + exponential, or other combinations). For very large earthquakes such as the Tohoku 2011 earthquake, the use of a single exponential decay model is not adequate to model significant and ongoing postseismic displacements. It would be good to have scope for several parameters to better model postseismic decay in the functional model. Start and end epochs for the velocity model component would also be useful.

Note also the comments at https://github.com/opengeospatial/CRS-Deformation-Models/blob/master/functional-model/strawman-cc/functional-model-strawman-cc.adoc#discuss-time-function in the strawman 

How complex should the time function be.  Should it support multiple components as Richard suggests (and is there are reason not to).

**Comment by kevinmkelly** [comment]
Please reference Appendix C of:

Altamimi, Z., P. Rebischung, L. Métivier, and X. Collilieux (2016), ITRF2014: A new release of the International Terrestrial Reference Frame modeling nonlinear station motions, J. Geophys. Res. Solid Earth, 121, 6109–6131, doi:10.1002/2016JB013098.

A PDF of this paper can be found [here](https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1002/2016JB013098). Eqn. C2 of this paper allows for any number of exponential and logarithmic terms in any combination. In my opinion, we should follow the academic lead here and accommodate this generalized modeling of postseismic displacement (i.e. time functions). Note also that the uncertainty of the postseismic displacement is developed in Eqns. C3-C7.

**Comment by rstanaway** [comment]
Kevin, Thank you for the ITRF link. There have been a few other excellent studies of postseismic displacement function modelling including (in time order): 

Richard Snay, Jeff Freymueller and Chris Pearson, Crustal Motion Models Developed for Version 3.2 of the Horizontal Time-Dependent Positioning Utility, J. Appl. Geodesy, Vol. 7 (2013), pp. 173–190
[https://www.degruyter.com/view/journals/jag/7/3/article-p173.xml](https://www.degruyter.com/view/journals/jag/7/3/article-p173.xml)

Mikio Tobita, Combined logarithmic and exponential function model for fitting postseismic GNSS time series after 2011 Tohoku‑Oki earthquake, Earth, Planets and Space (2016) 68:41
[https://earth-planets-space.springeropen.com/articles/10.1186/s40623-016-0422-4](https://earth-planets-space.springeropen.com/articles/10.1186/s40623-016-0422-4)

Wan Anom WAN ARIS, Tajul Ariffin MUSA, Kamaludin MOHD OMAR, Abdullah Hisam OMAR, Non-Linear Crustal Deformation Modeling for Dynamic Reference Frame: A Case Study in Peninsular Malaysia, Proceedings from the FIG Congress 2018, Istanbul, 2018.
[http://fig.net/resources/proceedings/fig_proceedings/fig2018/papers/ts10e/TS10E_wan_aris_musa_et_al_9268.pdf](http://fig.net/resources/proceedings/fig_proceedings/fig2018/papers/ts10e/TS10E_wan_aris_musa_et_al_9268.pdf)

Kwo-Hwa Chen, Ray Y. Chuang and Kuo-En Ching, Realization approach of non‑linear postseismic deformation model for Taiwan
semi‑kinematic reference frame,  Earth, Planets and Space (2020) 72:75
[https://doi.org/10.1186/s40623-020-01209-y](https://doi.org/10.1186/s40623-020-01209-y)

**Comment by kevinmkelly** [comment]
Thanks, Richard. Of course, since you are intimately acquainted with all these works, perhaps the group at large can look to you to summarize and recommend an answer to Chris' question: "How complex should the time function be?" And the rest of us can avoid having to read through them all!

**Comment by ccrook** [comment]
@kevinmkelly Good thought to look at the ITRF station model.  It is a slightly different use case, as it is representing the deformation at a point.  If we are using the time model to multiply a spatial model then it is unlikely to represent well the time function across the extent of that model - by decomposing to spatial functions time time function we are necessarily simplifying things, hence my original approach with a simpler time function. https://github.com/opengeospatial/CRS-Deformation-Models/blob/master/functional-model/strawman-cc/functional-model-strawman-cc.adoc#decomposition-into-components

This raises another couple of issues for me:

* Currently the functional model doesn't include an error component for the time function - it treats it as an error free multiplier of the spatial function.  How much do we want to add to the time function complexity in this direction (eg errors of parameters, covariances of parameters of the time functions)

* Is there a completely different formulation of a deformation model we want to include (which I think @rstanaway has mentioned before) which is a triangulated interpolation between a set of reference stations with individual trajectory models.  Currently I don't think this approach is used anywhere, but is a valid alternative approach.

**Comment by demiangomez** [comment]
Dear all,

This is a very interesting subject and I would like to briefly chime in. I'm sorry I've been absent during the last couple meetings but I'm teaching at the same time as we have the meetings. Regarding the necessity of using combinations of exp+log or log+log functions, I would like to bring up a recent study we did with one of our students that shows that log+log usually works better (or at least as good as) exp+exp or log+exp under certain conditions. https://link.springer.com/article/10.1007/s00190-020-01413-4

Also, I would like to address this phrase in the strawman: "it is not clear that these are a much better model for deformation over the extent of a spatial model". Allow me to bring up the deformation model for Argentina where we used a log decay component to generate a spatially continuous post-seismic deformation model for the 2010 Chile earthquake. In this case (and for other earthquakes that we have still not published) we produced an interpolated surface (using the log amplitudes) that performed very well to "predict" the post-seismic deformation over a continuous spatial surface: https://link.springer.com/content/pdf/10.1007/s00190-015-0871-8.pdf. We didn't use a triangulated interpolation but rather a least squares collocation approach. We are now extending this technique to a double log transient.

**Comment by kevinmkelly** [comment]
Thanks very much Demian. My main point was that the DMFM should not restrict the time functions, despite the fact that it can be shown that some perform equally well while others perform poorly. The DMFM should accommodate any number of exponential and logarithmic terms in any combination. In fact, the DMFM should also accommodate displacement due to slow-slip events, which may be modeled using a very different time function, e.g. an error function (see [_Denys and Pearson_, 2016](http://fig.net/resources/monthly_articles/2016/march_2016/denys_pearson_march_2016.pdf)).

**Comment by rstanaway** [comment]
Hi @demiangomez . Thank you very much for the links to your work in Argentina. As Kevin suggests, I'll do a comparative study and summary of the ITRF, Alaska, Japan, Taiwan, Malaysia and Argentina studies prior to the next DM project meeting. Strait interpolation of a TIN composed of CORS is definitely too simplistic and as you say a LSC approach is more robust. Even then it's better to deconvolve the different contributions to the deformation (using geophysical models) that is observable in the CORS site motion. One of the difficulties is separating out aftershock displacements and SSE that happen within the postseismic period after the mainshock. That leads onto the question of SSE which tend to be frequent though not of great magnitude. The NZ approach has been to basically average the SSE affected time-series out provide that the residuals don't exceed a few cm. This is OK for that level of precision.

**Comment by ccrook** [comment]
@demiangomez Thanks for these very interesting cases which I hadn't seen.   I have only read the abstract (I haven't purchased the paper) and I am very interested in the least squares collocation approach.  Can I check my understanding?

To work out the displacement at a given epoch and at a location without CGPS you first calculate the displacement at each CGPS station, and then use least squares collocation to interpolate this to the location of interest?

So this is a completely different approach to representing the deformation to that in the straw man proposal, which decomposes the deformation into a spatial models with time functions.   Though I suppose it could be converted to a kernel spatial function for each CGPS station representing its spatial influence (through the collocation) multiplied by the time function that station.  

Am I anywhere close to understanding this?

**Comment by ccrook** [comment]
@kevinmkelly 

> My main point was that the DMFM should not restrict the time functions, despite the fact that it can be shown that some perform equally well while others perform poorly. The DMFM should accommodate any number of exponential and logarithmic terms in any combination. In fact, the DMFM should also accommodate displacement due to slow-slip events, which may be modeled using a very different time function, e.g. an error function (see Denys and Pearson, 2016).

I agree and and have amended the straw man to have the time function as the sum of any number of components.  At the moment these do not include logarithmic or cyclic components - I suspect we will want to add these.  I think we have to restrict the base set of functions available to make implementation possible, but we don't need to restrict the number of each of these used in a deformation component time function.

**Comment by demiangomez** [comment]
@ccrook you can download it from [here](https://www.ign.gob.ar/descargas/geodesia/2015_Acceso_a_marcos_de_referencia_bajo_los_efectos_de_grandes_terremotos.pdf). 

Actually, in most regions in South America, it is not possible to interpolate the displacements directly if you have a co-seismic event between ts and te, where ts is the start epoch and te the end epoch (i.e. we wish to go from ts -> te). This is because the number of observation points (i.e. the GNSS sites) is low and, with such low sampling, the co-seismic deformation field is non-stationary. Therefore, our approach was to use a geophysical model for the co-seismic component of the displacement (which yields a grid) and another grid for the amplitudes of the log decay functions obtained using LSC. In other words, each GNSS station yields a point observation of the post-seismic deformation field (the log amplitude A in A*log(1+dt/T)). These point observations are then interpolated using LSC to produce a grid of logarithmic amplitudes. Then, to obtain the displacement from ts to te, we first interpolate the grids to obtain the amplitudes of each component (linear, co-seismic, post-seismic, etc) and then we multiply those by their corresponding time functions. The sum of all components yields the desired displacement.

In sum, your idea of working with the displacements directly only works if you have a dense enough network (or a very smooth and well behaved deformation field).

Let me know if you have any more questions.

**Comment by ccrook** [comment]
@demiangomez Thanks for the clarification and link to your paper.  Some light reading for my weekend :-)

**Comment by ccrook** [comment]
MC: Second order velocity (acceleration) eg Greenland

**Comment by ccrook** [comment]
Add Logarithmic, cyclic, acceleration for V1
Note: this could be extended in future versions

Composite time function
Start and end epoch
