### ISSUE TITLE
Licence information recommendations in the functional model specification

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#22]
The functional model definition includes a specification of required metadata, and in particular licence information.  While this is arguable "non-functional" it This was discussed in the 2/11/2020 meeting at which the following points were noted:
* ESRI will not package data sets if they do not include a clear statement that the data can be released for public use (which need not be a formal licence IIRC)
* PROJ data sets (eg in cdn.proj.org) require a licence compatible with the [Open Source
Definition](https://opensource.org/osd-annotated)

This highlights the importance of including licence information with a published deformation model.  However the deformation model specification may also used for unpublished models within an organisation. 

How should this be reflected in the functional model specification?
* a requirement or a recommendation.  
* should a specific licence or set of licences be proposed, and if so what

**Comment by desruisseaux** [comment]
If we represent metadata in ISO 19115 structures, there is a location for licensing information (following is not a complete list):

```
MD_Metadata
└─ identificationInfo
   └─ resourceConstraints
      ├─ accessConstraints
      ├─ useConstraints
      ├─ useLimitation
      └─ reference`
```

`useConstraints` value can be one of `COPYRIGHT`, `INTELLECTUAL_PROPERTY_RIGHTS`, `PATENT`, `PATENT_PENDING`, `TRADEMARK`, `LICENCE`, `LICENCE_UNRESTRICTED`,`LICENCE_END_USER`, `LICENCE_DISTRIBUTOR`, `RESTRICTED`, `UNRESTRICTED` among others.

`useLimitation` is a place where to write, for example, _"not to be used for navigation"_.

`reference` is, in my understanding, the place where to put the license title and a link to the license.

Above was for legal constraints. ISO 19115 also has structures for security constraints (`UNCLASSIFIED`, `RESTRICTED`, `CONFIDENTIAL`, `SECRET`, etc).

**Comment by ccrook** [comment]
@KRyden I've assigned this to you as I think you said you could find some appropriate words for a statement on licence?  Thanks

**Comment by ccrook** [comment]
Not a concern of deformation model specification so removed from spec.  Is responsibility of carrier.
