### ISSUE TITLE
Metadata vs discovery metadata

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#30]

**Comment by desruisseaux** [comment]
I think we have:

* _Discovery metadata:_ handled by ISO 19115.
* _Operational metadata_ (I came with that name, there is maybe better name): specific to GGXF format with references to other standards such as ISO 19111.

For the discovery metadata part, it may be sufficient for the "CRS deformation model" group to said "here we put an ISO 19115 `MD_Metadata` object" (it would by GGXF job to specify the encoding details). Those metadata can include approximate geographic, vertical and temporal extent, a "global accuracy", producer information, security and legal constraints (licence), update frequency, lineage, _etc._ If we want to go in more details, maybe in a meeting we could go through those metadata and select which elements are most relevant?

**Comment by ccrook** [comment]
At December 2021 meeting it was decided that the deformation specification doesn't need to define discovery metadata - this can be the responsibility of the carrier format/implementation.
