### ISSUE TITLE
Open vs Closed standard

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#31]
In the 12 April 2021 meeting the question was raised "Should the deformation model functional model standard be an open standard or a closed standard".  

This high level arose while discussing the (relatively simple) issue of units of displacement.  

A closed standard would prescribe units by defining a supported code list (for example metres, mm, etc with a well defined relationship to metres).  Alternatively the closed standard could specify an arbitrary scale factor to be applied to the gridded displacements to convert to metres, which practically is no different to specifying metres as the unit.  

An open standard would allow the producer to specify the units in any way they wished, with maybe a reference/citation where the units are defined.  For example they could specify the units as log(metres) (deliberately unrealistic).  This would be unlikely to be supported by any software, but would still fully express their deformation model.

Perhaps a more realistic example would be in terms of the methods for defining the spatial model of a deformation component.  The current specification supports a gridded model and a triangulated model with a defined set of interpolation functions.  An open standard could allow a user to specify a different interpolation method (eg biquintic), or possibly even that the model is defined by a set of data points and a kriging interpolation method 

@RogerLott do you think this correctly represents the difference between open and closed standards?

**Comment by ccrook** [comment]
My view is that this decision should be driven by the purpose of the standard.


I think the purpose of this team is to define a standard that producers can use to create models with the confidence that compliant software software will support it.  I believe that this is a closed standard.  That is not to say that standard cannot be revised with new versions in the future.  Software vendors would then have the option of upgrading their compliance to the new version.

It may also be appropriate to offer a number of levels of compliance for software (eg supports calculating and applying displacements but does not support calculating or propagating uncertainties).

I believe our challenge is to find the balance of complexity between

- complex enough to support current and planned deformation models in use or planned 
- simple enough to encourage uptake by the software community

Possibly also "simple enough that the standard specification is not too off-putting to readers!"

At the moment there is the ultimate open standard (ie no standard).  Each producer generates models in their own format and typically develops their own software to evaluate it.  A software manufacturer then has to implement each model independently into their software.  In effect the standard is "a data set in a referenced defined format that can be evaluated to compute a displacement at a specific time and location", and the producers documentation is the citation supporting their choice of implementation.

Even if we don't meet the needs of every possible deformation model, if it is adoptable and adopted by a sufficient portion of the producer community then that could encourage software developers to adopt it even if it is slightly more complex than the producers individual models might be.

**Comment by RogerLott** [comment]
@ccrook I suggest that a closed standard is prescriptive, e.g. requiring data to be in particular units (metres). An open standard would allow any units (e.g. mm, degrees, etc) but require the producer to declare the unit name, unit type, and its conversion ratio to the SI base unit of that unit type (e.g. "millimetre, length, 0.001" as the SI base unit for length is the metre, or "second of arc, angle, 4.8481368110954E-6" as the SI base unit for plane angle is the radian). 
Using a code list is a halfway house which permits the unit type and its conversion ratio to be declared in the specification documentation for 'popular' units, which could permit their omission from the data file and the requirement reduced to just unit name. A code list allows the defined list to be extended by implementers (whereas an enumeration cannot be extended). But to be useful that extension needs to have the unit type and conversion to SI defined. I suggest that this makes implementation slighly more difficult, having to deal with both (a) items on the list and (b) possible extensions to it, wheras an open standard has just one syntax to parse.

Same applies to other attributes such as vector resolution. A closed standard mandates the parameters to be dE, dN, dU. An open standard would allow any parameters defined by the user (producer). This may not be useful (as the consumer may not know how to handle them). But here the half-way house can be a definition of the parameter in the specification conventions, and in in context of of an exchange format in any user-defined order, e.g. dX, dY, dZ or dN, dE, dU. This is how the current draft of GGXF is written.

**Comment by RogerLott** [comment]
Assuming the definition of open and closed as I give above, my preference for GGXF implementation is for units to be open (so allowing e.g. mm per year rather than metres per second) and for other attributes the half-way house of requiring attributes defined in the conventions. Although that is semi-closed, in this narrow field I think we can get all likely attributes included i the conventions. My concern with a closed standard is that it may inhibit adoption of the specification because "we would have to change our data".

**Comment by RogerLott** [comment]
(But GGXF implementation is not necessarily the same as DMFM specification)

**Comment by desruisseaux** [comment]
It is not answering the open versus closed question, but on the unit of measurement topic, would it be too restrictive to said that displacements should be in the units and axis directions of the interpolation CRS, with optionally a scale factor (relative to the units of the CRS, not necessarily relative to base units) for allowing e.g. to express displacements in centimetrers instead of metres?

**Comment by ccrook** [comment]
@desruisseaux I think that is too restrictive.  Typically the sourceCRS/targetCRS units (not interpolation, as the displacement is added to the sourceCRS to get targetCRS) are degrees and the displacement is metres.   My inclination is to allow the horizontal displacement to also be defined in degrees as an option (makes for efficient calculation), though it doesn't work near poles.  Also most if not all producers are using degrees or a multiple of them.  Other units (mm, feet, etc) are not really required I think, but it may avoid a conversion for some producers (even if it is a trivial one).

**Comment by ccrook** [comment]
@RogerLott On the open vs closed options, I think units are perhaps relatively simple.  All the options shown above are implementable.  How about interpolation method.  To be implementable that must be a constrained to a defined code list IMO.  Does that make it a closed standard?  I think it does, even though it is not prescribing the specific method (ie must be bilinear).

**Comment by droman77** [comment]
@RogerLott The purpose of a standard is not only to make sure there is internal consistency in the format of data from a single producer but also in data formatted by different producers. I think that leaving as an open option would make the inter-comparisons more problematic. A closed option should facilitate intercomparison with revisits to update as necessary. A producer can have their own internal standard but should make it assailable to others and for registries in a closed format.

**Comment by ccrook** [comment]
I'd like to close this issue.  I'm not sure we have reached a conclusion, but I'd like to propose the following:

For the purposes of this discussion I wonder if we can regard "closed" as being "completely implementable in code".  

By contrast  "open" would be that a producer could add features which would require software changes to implement.  For example a producer could add another option to a time function type code list, which would require an update to software to be able to calculate the time function. 

A "closed" specification need not preclude supporting a producer adding more metadata or attributes with the understanding and expectation that a software implementation would ignore them. 

With that understanding I think we should aim for a "closed" standard.  Our primary purpose is to allow producers to generate deformation models that can be directly used by consumers in their software, and that requires the standard to be closed.

(I am aware that usage of "open" and "closed" may not be standard - but I'm hoping this can convey are intent)

**Comment by ccrook** [comment]
Closing as per comment above.  Also noting that that carrier implementation may inherently support additional information that isn't used by deformation imlementation.
