### ISSUE TITLE
Should the deformation model format support plate motion models

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#36]
There are a number of global plate motion models that are used in geodetic applications (GNSS processing, network adjustment software).  These models define deformation as Euler pole rotation rates within tectonic plates defined spatially as a latitude/longitude polygon.  

Our current deformation model format is focused on local (eg national) deformation models, which for horizontal deformation are typically gridded perturbations, often relative to a single tectonic plate. 

Should the model be expanded to include plate motion models to provide the point motion models required by these applications.

**Comment by rogerfraser** [comment]
Thanks for raising this @ccrook. Recognising (1) the wide range of global plate motion models in use (e.g. PB2002, NNR-NUVEL-1A, NNR-MORVEL56, ITRF2014, GSRM 2014, etc.) by various software packages, and (2) the absence of a consistent standard and encoding format for such models, this would be very much appreciated. 

By way of example, [icsm-au/DynAdjust](https://github.com/icsm-au/DynAdjust) uses a basic text file format defined by Peter Bird for the PB2002 model.  See sections 4.3.1 and 4.6.3 in the [DynAdjust User's Guide](https://github.com/icsm-au/DynAdjust/raw/master/resources/DynAdjust%20Users%20Guide.pdf) for the way this information is used.  Two sample models provided in the basic text file format are:
- No-net-rotation, **NNR MORVEL56**
   - Global [plate polygons](https://github.com/icsm-au/DynAdjust/blob/master/sampleData/MORVEL56_plates.dig)
   - Euler pole [rotation rates](https://github.com/icsm-au/DynAdjust/blob/master/sampleData/NNR-MORVEL56_poles.dat) for each plate
   - Source: http://geoscience.wisc.edu/~chuck/MORVEL/NNRMRVL56_AVs.html
- Relative rotation, **PB2002**
   - Global [plate polygons](https://github.com/icsm-au/DynAdjust/blob/master/sampleData/PB2002_plates.dig)
   - Euler pole [rotation rates](https://github.com/icsm-au/DynAdjust/blob/master/sampleData/PB2002_poles.dat) for each plate
   - Source: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2001GC000252

Having this information represented in a standard format not only has obvious interoperability benefits (which you're well across), it would increase the use (and re-use) of standard packages and libraries.

Thanks Chris - looking forward to others' comments on this.

**Comment by rstanaway** [comment]
A plate-motion model (PMM) can be used as a standalone model within most stable plate settings for most time-dependent transformations within stable portions of the plate. This approach has been used for ITRF2014 to GDA2020 transformations with the Australian PMM embedded as rotation rates within a 14 parameter framework (zeroes for other parameters). The approach is ideally suited to Australia with it's tectonically stable intraplate setting (though not always!)

A PMM is parent frame dependent so different PMMs for the same plate usually have different source RF (such as NNR based on ITRF2014). The different source RF and are not necessarily consistent resulting in differing velocities depending on the RF. For example it wouldn't be advisable to use an ITRF2005 PMM with ITRF2014 data.

Velocity grids (that form part of a deformation model suite) can be directly ITRF based (I believe that the NZ model is ITRF96 based to suit the definition of NZGD2000) or plate-fixed. If used in a plate-fixed context they can be combined with the PMM to enable plate-fixed RF to ITRF/NNR time-dependent transformations. The straight ITRF model doesn't need a PMM. Some care would be needed if the plate-fixed velocity grid is used in deforming parts (margins) of the plate as the velocities would be non-zero unlike stable parts of the plate. Plate-fixed RF coordinates at different epochs in deforming zones would need to be propagated to the common ITRF/plate-fixed epoch before transformation (a two-step process). The straight ITRF velocity model could be implemented as a one-step process, so well suited to plate-boundary zone countries like Japan, New Zealand, Greece...

**Comment by ccrook** [comment]
To be clear - this is referring to a global PMM defining plate boundaries and rotation rates, not a single plate rotation rate within a stable (or largely stable) plate that defines the bulk of the deformation model (even if technically not deformation).  The latter has already been covered in #23

**Comment by ccrook** [comment]
Meeting notes: 2021-06-07

KK, CP, DC, CC: Think should be dealt with separately
KK: Possibly for separate consideration after "local" model sorted.

Summary is that this is does not fit within current scope of deformation model and will require a different encoding altogether, so standardising PMMs is a different exercise to "local" deformation models.  

When the work on local models is complete the team could consider proposing a standard encoding for such models.

**Comment by ccrook** [comment]
For now this issue is closed.
