### ISSUE TITLE
Refactor time functions to consistently use functionReferenceEpoch.

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#45]
I'd like to propose a modification to the time functions to rationalise the use of the functionReferenceEpoch.  

I suggest that every function has a functionReferenceEpoch parameter at which its value is 0.

For step, ramp, exponential, and logarithmic functions it is optional.  These functions will all have a startEpoch which is the epoch at which the step, exponential, or logarithmic event starts.  The exponential and logarithmic also have an optional endEpoch parameter after which time they remain constant.

This issue proposes that for all time functions the functionReferenceEpoch is the epoch at which the function is zero.   This is implemented by adding a constant to the time function.  For example an exponential function is defined at the moment as:

 f(_t_) = s.(1 - exp(-(_t_- t<sub>s</sub>)/θ))  for _t_ > t<sub>s</sub>

where t<sub>s</sub> is the start epoch.  If the reference epoch t<sub>0</sub> is defined this is replaced with

> F(_t_) = f(_t_)  - f(t<sub>0</sub>)

This would work similarly for all functions except for the cyclic function.  This would be replaced with a simple sine function, ie

> F(_t_) = s.sin(_f_(_t_ - t<sub>0</sub>)/2&#120587;)

where _f_ is the frequency, and s is the optional function scale factor.  

With this approach the reverse step function will be removed, as this is simply a step function for which the function reference epoch is after the start epoch.

I see two advantages to this proposal:

1) It simplifies adding historic events to the time function, or making new versions of a deformation model in which events are historic.  Only the functionReferenceEpochs need to change.

2) It provides a more consistent structure for time functions.

It may be sensible to take this one stage further and make the functionReferenceEpoch a element (GGXF group) parameter rather than a parameter of individual time functions.  In this case it would be a required parameter for deformation models.  ie in GGXF
``` yaml

groups:
  - groupName: some group
    parameters: ...
    grids: ...
    timeFunctionReferenceEpoch: ####-##-##
    timeFunctions:
       - functionType: velocity
         ...
       - functionType: step
         ...
```

**Comment by ccrook** [comment]
Amended version of time functions are in https://docs.google.com/document/d/1iuc1x3HsGZlCLQPHI-KKs2QwXFexRv18em51zWjnsjM/edit#heading=h.45jfvxd.

**Comment by kevinmkelly** [comment]
The revised time functions look fine. However, the use of the function reference epoch could be explained further, especially how it applies to historic events. In fact, it may be instructive and add clarity to provide a real data example for each time function.

**Comment by ccrook** [comment]
@kevinmkelly Good thought on documenting this a bit better.  Maybe this could be an additional section in Appendix A?

**Comment by ccrook** [comment]
@kevinmkelly I have put some more explanation of time functions in https://docs.google.com/document/d/1wlcB3zQjXqMmV-P6IHcLjUo-yC7PLeut_u9hazTbiEE/edit#bookmark=id.2yutaiw.  Very much open to amendment!

**Comment by kevinmkelly** [comment]
Thanks, Chris. I've posted a few comments in the Google Doc.

**Comment by ccrook** [comment]
@kevinmkelly I haven't updated the google doc yet, but I have had another go at describing the time functions taking on board some of your comments.  You can see what this looks like in the PDF at https://github.com/opengeospatial/CRS-Deformation-Models/blob/master/products/specification/abstract-specification-deformation-model-functional-model.pdf (section A.5).  Unfortunately you can't comment on it directly there so please could you put any comments in this issue if you have time to look at it.
(Update - these changes are now in the google document at https://docs.google.com/document/d/1wlcB3zQjXqMmV-P6IHcLjUo-yC7PLeut_u9hazTbiEE/edit#bookmark=id.2yutaiw)

**Comment by ccrook** [comment]
There is an untidiness in the refactored time functions that I am finding hard to live with!   

This is the fact that the function reference epoch is handled differently in the velocity, acceleration, and cyclic functions.   In particular for the acceleration and cyclic functions the effect of changing the function reference epoch is not simply adding adding a constant value to set the function to zero at that epoch.

I am wondering if it would be better to define another epoch for these functions that is used to define the time used in the base function calculation.   I am haven't a good name for this - the best I have come up with so far is "calculation epoch".   

For the cyclic function it may also be better to restore the sine and cosine functions based on the calculation epoch.  This would allow a conventional time series representation as A.sin(t-t<sub>0</sub>) + B.cos(t-t<sub>0</sub>) + ...  On the other hand this may be overbaking a function that isn't used in any deformation models currently as far as I know.

Links:
[Current definition](https://docs.google.com/document/d/1wlcB3zQjXqMmV-P6IHcLjUo-yC7PLeut_u9hazTbiEE/edit#heading=h.6wlk2xmarcsn)
[Description of epochs](https://docs.google.com/document/d/1wlcB3zQjXqMmV-P6IHcLjUo-yC7PLeut_u9hazTbiEE/edit#heading=h.c0v5uq51i98a)

Thoughts?

**Comment by kevinmkelly** [comment]
My initial thoughts are that if different definitions of epoch are needed for different time functions, as long as we very clearly define and explain what each "epoch" refers to, it seems fine to me to use them. It may be helpful to point out with each epoch definition how it differs from others, provided that that does not generate unnecessary confusion. If well defined, I'm not sure we need to give every epoch its own special name, but perhaps each should have it's own unique mathematical symbol.

**Comment by kevinmkelly** [comment]
@ccrook: I think section A.5 flows much better now. However, I'm still having trouble reconciling Figure A.3 with the text. The base function is shifting around but the explanations for it are not so clear. For example, the top and bottom left plots show the base function at zero but the text says it is never zero. In the top right plot, why does adding a start epoch "cause" the base function to shift up from zero? Perhaps some clearer explanations? For example, for the plot with end epoch te added we could say something like:

> When an end epoch te is defined for a base time function, the function remains constant at its value at te for all t>te.

And similar explanations for each plot in the figure. Also, are there constraints on defining these epochs? Can all epochs tv, ts, te, t0 be defined, and if so, how would they be interpreted, i.e. if t0 is defined are ts and/or te relevant? I'm speaking here as if I'm a user with no knowledge of deformation models and just need to implement it in software. Is this clear enough?

**Comment by ccrook** [comment]
@kevinmkelly Thanks for feedback. 

On your last point, as "a user ... just need to implement it in software" I don't think you would be looking at this section, I think you would be looking at the [normative specification of time functions](https://docs.google.com/document/d/1wlcB3zQjXqMmV-P6IHcLjUo-yC7PLeut_u9hazTbiEE/edit#bookmark=id.2250f4o).  This pretty much has the sentence you suggested!

This section is primarily written for producers (as per the title of Appendix A), for whom the mathematical definitions of how to calculate the time functions in the normative section may not be so useful.  From a producer's point of view the question is not how to calculate a time function, but how should I encode a time function for my purposes, and why would I use these parameters.   

Your comments certainly tell me where it needs to be clearer.  The problem with plotting something "asymptotically close to zero" is that it becomes visually indistinguishable from zero.  So either I could show a much broader hyperbolic tangent, or perhaps more usefully add a bit more explanation in the text.  

So I agree - it needs a bit more "why", and a bit more guidance (eg noting that when using the start epoch or end epoch you would typically also use the function reference epoch.  Also note that in some cases it doesn't make any sense to add these parameters, for example start and end epoch don't make sense with a step function.

I'll have another go at this later today.

Thanks again

**Comment by ccrook** [comment]
@kevinmkelly I have expanded a bit on [Appendix A.5](https://docs.google.com/document/d/1wlcB3zQjXqMmV-P6IHcLjUo-yC7PLeut_u9hazTbiEE/edit#bookmark=id.2yutaiw).  See if this reads more clearly for the producer audience.

**Comment by kevinmkelly** [comment]
@ccrook Great, Chris. This explains the various times functions much better and the examples are clear and informative. Apart from some wordsmithing - which I am making considerable effort to suppress at this stage - I think Appendix A.5 reads well and helps instruct. OK, just one minor wordsmith suggestion (for now); hope it helps:

> The start and end epochs can be used to remove any change before the start epoch or after the end epoch.  Setting a start epoch (graph B) applies the base function value at that epoch to any time before the start epoch.  Similarly, setting an end epoch (graph C) applies the base function value at that epoch to any time after the end epoch.

**Comment by ccrook** [comment]
@kevinmkelly thanks - suggestion applied to draft document.

**Comment by ccrook** [comment]
Agreed in March 14 meeting that no further amendments required to time functions.
