### ISSUE TITLE
Compile list of addresses for deformation model survey

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#5]

**Comment by anomaris** [comment]
What is the inter-distance of GNSS CORS to quantify the deformation signal towards deformation model?

**Comment by rstanaway** [comment]
I can circulate the questionnaire amongst the IAG WG members. The WG constitutes many people in national or regional geodetic agencies. I'll also contact staff in other countries who I know. If we're looking at currently accessible positioning accuracy there's actually no country that can avoid using a deformation model approach!

**Comment by ccrook** [comment]
I propose we create an online questionnaire (either Google Docs or Survey Monkey).  We can then distribute the link to everyone we consider may be able to contribute.   That should be available middle of next week, say 19 August, a few days after the comment period for the questionnaire is closed.

**Comment by kbevers** [comment]
I'll make sure to forward the questionaire to the the reference frame working group of the Nordic Geodetic Commision and the PROJ mailing list.

**Comment by JATarrio** [comment]
I think a google form would be ideal, I can send it to SIRGAS colleagues; and my contacts from Southern Europe (although there they don't have too many problems with RF time-dependent, jejeje)

**Comment by ccrook** [comment]
Edited comments extracted from 10 August meeting chat on potential recipients of the survey questionnaire.

* Richard Stanaway: The IAG WG has many connections
*  Chris Pearson: Include private company users, eg Trimble
*  Richard Stanaway: Resource companies also use national gedoetic standards.  Also major GIS and posiitoning companies.
*  Kevin Kelly: Though primarily a GIS/GNSS provider will "simply" ingest and code official model(s) in software and provide an interface/platform for their application. But there could be an expanded role, which needs some further consideration.
* Nic Donnelly: We could circulate it through FIG Comm 5 (Positioning and Measurement) national representatives, who are often government geodetic agency reps

**Comment by ccrook** [comment]
I am closing this issue as this discussion is happing in #1 (compile a questionnaire)
