### ISSUE TITLE
Post draft specification to OGC drafts server?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/CRS-Deformation-Models#52]
I'm having a hard time accessing the draft specification. Can someone please arrange for it to be built and deployed to the draft specification server as is done with other specifications? https://docs.ogc.org/DRAFTS/ I believe @gbuehler can help get it set up.

Links to the built draft in a prominent location in the README here would be a great help in understanding what this group is doing.

**Comment by ccrook** [comment]
Hi Dave.  I'll investigate that.  In the meantime it is at https://github.com/opengeospatial/CRS-Deformation-Models/raw/master/products/specification/abstract-specification-deformation-model-functional-model.pdf (as per link on github README).  

Are you having difficulty accessing that?  Or just that it should be in the DRAFTS specification, which makes sense to me though I wasn't aware of it.

**Comment by dblodgett-usgs** [comment]
I wouldn't say I'm having trouble accessing it, but I do find it much less accessible than the html drafts that OGC has set up infrastructure for. 

Thanks for looking into it.

**Comment by ccrook** [comment]
The draft specification is now available at:

https://docs.ogc.org/DRAFTS/22-010.html or
https://docs.ogc.org/DRAFTS/22-010.pdf

Ideally any questions or issues on the specification should be raised as issues in this repostory

**Comment by dblodgett-usgs** [comment]
🙏 Thanks @ccrook !!
