### ISSUE TITLE
What is a 'functional model' ? 

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/CRS-Deformation-Models#53]
Looking through the draft standard, it's not clear what is meant by a "functional model". I'm aware of literature and precedent of conceptual, logical, and physical models, and could make some assumptions about what is meant by functional, but a definition (preferably one backed by some common practice) would benefit my understanding of what this work is.

**Comment by ccrook** [comment]
Hi Dave.  Good point and one that did get discussed several times during the evolution of this specification.  It is certainly a term that I have heard and used many times over the years but it is definitely something that should be referenced or defined within the specification.  I'll bring this up next time the project team convenes.  In the mean time I'll leave this issue open.  Thanks

**Comment by dblodgett-usgs** [comment]
Right on. Thanks for considering specifying what it means.
